import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs';
import Navbar from "@/webcomponents/Navbar/Navbar";
import ResponsiveNav from "@/webcomponents/Navbar/ResponsiveNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DSA Website",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Add the favicon here
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">       

        <body className={inter.className}>
          <div className="bg-black" style={{paddingTop:"1rem"}}>
            <Navbar />
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
